
[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"

[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
style = "Italic"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[mouse]
hide_when_typing = false

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
blur = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 20
y = 20

[general]
live_config_reload = true
import = [
  "tokyo-night.toml"
]
